on:
  push:
    branches:
      - develop

jobs:
  job1:
    name: Difference check
    runs-on: ubuntu-latest
    environment: development
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
    steps:
      - name: difference check step
        run: echo "difference check complete"

  job2:
    name: Deploy
    runs-on: ubuntu-latest
    environment: development
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
    steps:
      - name: deploy step
        run: echo "deployment complete"
